/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
import java.util.*;
public class Problem2 {

public static void main(String[] args) {
        int sum = 0;
        ArrayList<Integer> fibo = new ArrayList<>(100000);
        fibo.add(1);
        fibo.add(2);
        for(int i = 1; i < 10000; i++) {
                if(fibo.get(i) + fibo.get(i - 1) < 4000000) {
                        fibo.add(fibo.get(i) + fibo.get(i - 1));
                }
                else{
                        break;
                }
        }
        for(int j = 0; j < fibo.size(); j++) {
                if(fibo.get(j) % 2 == 0) {
                        sum += fibo.get(j);
                }
        }
        System.out.println(sum);
}
}
